### ISSUE TITLE
Block state format is old

### ISSUE THREAD

**Issue by Xterionix** [Blockception/BC-Minecraft-Bedrock-Command#104]
![image](https://github.com/Blockception/BC-Minecraft-Bedrock-Command/assets/72647213/29c3f4b9-8765-4422-aef5-20d8a6e2259c)

**Comment by Xterionix** [comment]
["growth=1] is the new, correct syntax

**Comment by DaanV2** [comment]
Just for block states?

**Comment by Xterionix** [comment]
Believe so

**Comment by Xterionix** [comment]
I think it's mimicing Java's syntax

**Comment by Xterionix** [comment]
Should transfer this to the diagnoser repo, since that's where it'll have to be fixed

**Comment by DaanV2** [comment]
Its a probally a combination of, will have to check
