### ISSUE TITLE
Feature Add /hud

### ISSUE THREAD

**Issue by Xterionix** [Blockception/BC-Minecraft-Bedrock-Command#97]
As described in the title

**Comment by DaanV2** [comment]
I don't see it in the documentation, changelog, or Minecraft itself; where is it coming from 🤔 ?

**Comment by Xterionix** [comment]
https://learn.microsoft.com/en-us/minecraft/creator/commands/commands/hud?view=minecraft-bedrock-stable

**Comment by DaanV2** [comment]
Added
